services:
  nestjs-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      TYPEORM_SYNCHRONIZE: true
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    volumes:
      - ./rds-ca-cert.pem:/app/rds-ca-cert.pem

  nestjs-app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      TYPEORM_SYNCHRONIZE: false
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    volumes:
      - ./rds-ca-cert.pem:/app/rds-ca-cert.pem