FROM node:22.9.0-alpine3.19

WORKDIR /app

COPY package*.json ./

RUN npm install

## Copy all my dir to the container
COPY . .

COPY ./rds-ca-cert.pem /app/rds-ca-cert.pem

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:dev"]